### ISSUE TITLE
Add GDAL 3.6 to test matrix

### ISSUE THREAD

**Issue by roelarents** [PDOK/geopackage-validator#109]
GDAL 3.6(.2) was [set as base for the docker image](https://github.com/PDOK/geopackage-validator/pull/108). That build including tests pass. But GDAL 3.6 should also be added to the test matrix. A [naive attempt failed](https://github.com/PDOK/geopackage-validator/actions/runs/4243582050).

**Comment by RoelvandenBerg** [comment]
implemented
