### ISSUE TITLE
Validate that the geometry for each feature matches the geometry set for the layer in gpkg

### ISSUE THREAD

**Issue by velle** [PDOK/geopackage-validator#112]
I had a file, input.gpkg, where most features were Linestring, though I suspected some were MultiLinestring. I ran the following (without error):

```
ogr2ogr output.gpkg input.gpkg -nlt LineString
```

And then I thought I could use geopackage-validator to test if everything was ok. And it gave no errors. 

```
geopackage-validator validate --gpkg-path output.gpkg
```

But in fact it turned out later that the file did contain some MultiLinestrings, as shown below. 

```
ogr2ogr selected.gpkg output.gpkg -clipdst filter.gpkg
Warning 1: A geometry of type MULTILINESTRING is inserted into layer output of geometry type LINESTRING, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.
```

I was expecting geopackage-validator to detect this. Is this a bug or is this indeed intended behavior? If intented behaviour, then I hope you will consider implementing a check for this.

**Comment by RoelvandenBerg** [comment]
@velle do you have a small example geopackage that reproduces this? And can you tell me the python version and the gdal version you are using? 

RQ14 and RQ15 should test for this: 

<html>
<body>


RQ14 | The geometry_type_name from the gpkg_geometry_columns table must be one of POINT, LINESTRING, POLYGON, MULTIPOINT, MULTILINESTRING, or MULTIPOLYGON.
-- | --
RQ15 | All table geometries must match the geometry_type_name from the gpkg_geometry_columns table.


</body>
</html>

**Comment by velle** [comment]
Thanks for your quick answer. Based on your answer I looked further into the last ogr2ogr command, and now I believe that in fact the last ogr2ogr takes a Linestring, but for some features produces a Multilinestring.

![image](https://user-images.githubusercontent.com/4488298/234330822-d776ad32-d088-40a5-82e4-89deb2e4d9d8.png)
