### ISSUE TITLE
rely on own implementation for feature count

### ISSUE THREAD

**Issue by arbakker** [PDOK/geopackage-validator#2]
CBS gebiedsindelingen GPKG gives false negative result on the R2 check "Layers must have at least one feature."

```json
{
    "R2": {
        "errorinfo": {
            "errortype": "R2",
            "validation": "Layers must have at least one feature."
        },
        "errors": [
            "Error layer: cbs_toeristengroep_2020_labelpoint",
            "Error layer: cbs_veiligheidsregio_2020_labelpoint",
            "Error layer: cbs_veiligthuisregio_2020_labelpoint",
            "Error layer: cbs_zorgkantoorregio_2019_labelpoint",
            "Error layer: cbs_zorgkantoorregio_2020_labelpoint",
            "Error layer: cbs_toeristengebied_2020_labelpoint"
        ]
    }
}
```

CBS GPKG can be downloaded from https://www.cbs.nl/nl-nl/dossier/nederland-regionaal/geografische-data/cbs-gebiedsindelingen

The root cause is that the table `gpkg_ogr_contents` is not in sync with the actual state of the geopackage. Execute the following SQL:

```
sqlite3 cbsgebiedsindelingen_2020_v2.gpkg "select * from gpkg_ogr_contents where table_name = 'cbs_toeristengebied_2020_labelpoint'"
cbs_toeristengebied_2020_labelpoint|0
```
```
sqlite3 cbsgebiedsindelingen_2020_v2.gpkg "select count(*) from cbs_toeristengebied_2020_labelpoint"
17
```
The table `gpkg_ogr_contents` is where OGR/GDAL does the bookkeeping for the feature count of a table. But if the GPKG is altered by hand, or the database triggers to update this table are removed, the feature count of a table can be incorrect. 

The `layerfeature_check` relies on OGR/GDAL to determine the number of features in a table, which in turn relies on the table `gpkg_ogr_contents`. The code to determine the number of features should be a different implementation to check the actual number of features, since using OGC/GDAL is not entirely reliable. 

We could then add a additional check to see if the `gpkg_ogr_contents` table is in sync with the gpgk (provided this table is present, not all gpkgs use this OGR/GDAL convention AFAIK).

**Comment by Daan-** [comment]
Fixed by adding an extra validation (R11) which will report the mismatch in feature counts:

```
"R11": {
                "errorinfo": {
                    "errortype": "R11",
                    "validation": "OGR indexed feature counts must be up to date"
                },
                "errors": [
                    "OGR index for feature count is not up to date for table: cbs_toeristengroep_2020_labelpoint. Indexed feature count: 0, real feature count: 6",
                    "OGR index for feature count is not up to date for table: cbs_veiligheidsregio_2020_labelpoint. Indexed feature count: 0, real feature count: 25",
                    "OGR index for feature count is not up to date for table: cbs_veiligthuisregio_2020_labelpoint. Indexed feature count: 0, real feature count: 26",
                    "OGR index for feature count is not up to date for table: cbs_zorgkantoorregio_2019_labelpoint. Indexed feature count: 0, real feature count: 31",
                    "OGR index for feature count is not up to date for table: cbs_zorgkantoorregio_2020_labelpoint. Indexed feature count: 0, real feature count: 31",
                    "OGR index for feature count is not up to date for table: cbs_toeristengebied_2020_labelpoint. Indexed feature count: 0, real feature count: 17"
                ]
            }
```

The original validation will now look at the real feature count and not the count reported by OGR.
