### ISSUE TITLE
[Proposal] Add Polygon orientation check (CCW for extrerior and CW for interior rings)

### ISSUE THREAD

**Issue by mwjsanders** [PDOK/geopackage-validator#21]
If and when a standard orientation is chosen, this should be checked as an requirement in the validator.
background info:
https://inspire.ec.europa.eu/forum/pages/view/198988/orientation-of-polygons-counter-clockwise

**Comment by olthom** [comment]
@mwjsanders zie https://github.com/PDOK/interne-documentatie/blob/master/architectuur/architectuur-principes/besluiten/draairichting-exterior-polygonen.md
