### ISSUE TITLE
[Proposal] Log entry with kick-off message

### ISSUE THREAD

**Issue by boazhuisman** [PDOK/geopackage-validator#48]
When analyzing a large geopackage (1GB+), the validator (with command `geopackage-validator validate ...`) does not give feedback on that it has started analyzing the geopackage. 

Imho, it would be more user-friendly to start the validation with a small log entry like:
`'Validation started for {gpkg-path}..'`

Otherwise a user might not be aware if the validation has succesfully started or not.

**Comment by RoelvandenBerg** [comment]
Wont do for now, we log a `json` to stdout. This would interfere with that behaviour.
