### ISSUE TITLE
SQLite database is locked after validating

### ISSUE THREAD

**Issue by kit-rothwell** [PDOK/geopackage-validator#91]
After validating a GeoPackage, when subsequent actions are attempted on the database the following error is thrown:
`sqlite3_exec(COMMIT) failed: database is locked`

The issue can be reproduced with the below function:

```
from geopackage_validator.validate import validate
from osgeo import ogr


def gpkg_validate_issue(file_path):
    driver = ogr.GetDriverByName("GPKG")
    gpkg_src = driver.Open(file_path, update=True)
    validate(
        gpkg_path=file_path, validations='ALL'
    )
    gpkg_layer = gpkg_src.GetLayerByIndex(0)
    gpkg_src.DeleteLayer(gpkg_layer.GetName())
```

**Comment by RoelvandenBerg** [comment]
@kit-rothwell I cannot reproduce this with the above code fragment. Can you tell me what ogr version you are using? And perhaps provide a geopackage that has this problem?

**Comment by RoelvandenBerg** [comment]
@kit-rothwell thank you for your issue. The following release will have a fix for this issue.
