### ISSUE TITLE
Is the gdal version >= 3.2.1 a strict requirement?

### ISSUE THREAD

**Issue by giohappy** [PDOK/geopackage-validator#97]
I see the package has a dependency on GDAL>=3.2.1, which makes it a bit cumbersome to install on Ubuntu 20.04.
I wonder if the module is using features that are only available starting from that version or if the requirement could be relaxed to include GDAL 3.0.4 (which is shipped with Ubuntu).

**Comment by RoelvandenBerg** [comment]
The requirement stems from validations like the CCW recommendation (RC4) which will break when < 3.2.1. Installing gdal > 3.2.1 on Ubuntu 20.04 can be done by adding [ubuntugis-unstable](https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable) to your apt sources, which is more stable than the name suggests. 

We also provide a way to run with docker-compose (and by mounting volumes you can also develop with the docker-compose setup). 

I hope this helps!

**Comment by giohappy** [comment]
Thanks @RoelvandenBerg for the clarification.

Of course, if strictly needed, there are several solutions to get the requested versions.

**Comment by RoelvandenBerg** [comment]
For future reference. [We now test all supported versions for ubuntu, gdal/ogr and python](https://github.com/PDOK/geopackage-validator/actions/workflows/pytest.yml). I tried to make a workaround and support lower gdal versions but it took more time than I could muster. So I'm afraid these are the versions we now support.
